### PR TITLE
new dir structure idea

### PR DESCRIPTION
**Pull request by danlangford**
using suggested dir structure from hee: https://medium.com/heuristics/c-application-development-part-1-project-structure-454b00f9eddc

 - moved .pl to /web and sample data to /test
 - renamed files to avoid the .out extension

i DID NOT attempt to update any file paths in any `.bat` or `.pl` files. those are likely "broken". since all the `.pl` files were geared towards the "old" website and the new website is likely quite different in its API or layout I have mostly ignored those.

### CODE REVIEW

**Comment by danlangford** [comment]
structure is as follows

```
.
├── .gitignore
├── BUILDING.MD
├── CMakeLists.txt
├── HISTORY.TXT
├── LICENSE
├── NOTES.TXT
├── README.TXT
├── run.bat
├── src
│   ├── bmai.cpp
│   ├── bmai.h
│   ├── bmai_ai.cpp
│   ├── bmai_ai.h
│   └── bmai_player.cpp
├── test
│   ├── bmai_in.txt
│   ├── bmsim_in.txt
│   ├── bmsim_out.txt
│   ├── test_in.txt
│   └── test_out.txt
└── web
    ├── bmai.pl
    ├── bmai_run.pl
    ├── bmai_test.pl
    ├── dp_lib.pl
    └── stats.pl

```

**Comment by danlangford** [comment]
marked as DRAFT PR because this is very likely not ready to merge, but at least ready to discuss

**Comment by hamstercrack** [comment]
The structure seems fine.

**Comment by danlangford** [comment]
i have worked this structure on windows, mac, linux. a handful of different IDEs, some automated infrastructure. so if your ok with this structure you are welcome to merge it. i will use this structure in my fork of this repo

**Comment by hamstercrack** [comment]
merged

**Pull request merged**
